Ruby on Rails Project - Associations
arthurborgesdev/private-events pull request #1
Opened 2021-05-14 21:39 UTC by jmontanholi

## In this project me and my partner implemented the following:
* ### User model
* ### Event model
* ### Methods and views for both models
* ### Associations between both models with different foreign_key names (implemented with "has_many through")
* ### Navbar for easy navigation

2021-05-14 23:24 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello @jmontanholi 
Great work on this project. 
I can tell you put in a lot of work👏👏
Let's make some changes and get it approved.

[REQUIRED]: In your event index page, kindly add a way to see upcoming and past events
[REQUIRED]: In your event show page, kindly add a way to invite users and users to attend events.

Below are the additional changes.

Make the required changes and ask for another review👍
Happy coding💻💻💻

2021-05-14 23:25 UTC, NtwaliHeritier commented on app/controllers/events_controller.rb
> +    @events = Event.all
In your index function add `@upcoming_events = Event.upcoming_events`, `
@past_events = Event.previous_events` to get past and upcoming events in the view

2021-05-14 23:26 UTC, NtwaliHeritier commented on app/controllers/events_controller.rb
> +    @event = User.find(session[:current_user_id]).events.new(event_params)
In your create method use this line instead to get all user's events `
current_user.events.build(event_params)`

2021-05-14 23:36 UTC, NtwaliHeritier commented on app/controllers/events_controller.rb
> +  def show
In your show method add `
@created_events = current_user.events` for events created by current user, `
@past_events = current_user.attended_events.previous` for previous attended events by current_user and `
@upcoming_events = current_user.attended_events.upcoming` for upcoming events that the current user will be attending.

2021-05-17 22:01 UTC, GzimAsani requested changes
# STATUS: Changes Required :red_circle: 

## Hello **Team** thank you for making almost all the required changes by the previous TSE, however you have one additional change to make that was asked previously kindly find it below :arrow_down:

2021-05-17 22:11 UTC, jmontanholi commented on app/controllers/events_controller.rb
> +  def index
Hello Gzim, we did this but each one with a new method, could you please help us on how to implement this all inside the index? I can show you what we did in a meeting if you want. We are using different methods to be able to have multiple views instead of just one.

2021-05-17 22:16 UTC, GzimAsani commented on app/controllers/events_controller.rb
> +  def index
Hi @jmontanholi. I can see your point and why you did it, so please request another CDR and it should be approved

2021-05-17 22:17 UTC, jmontanholi commented on app/controllers/events_controller.rb
> +  def index
Okay! Thanks a lot, Gzim!

2021-05-17 22:20 UTC, GzimAsani approved these changes
# STATUS: APPROVED :green_circle: 

## Hi team, your project is now approved, good luck with the next projects :muscle: 

# Happy Coding :computer: :desktop_computer:

2021-05-17 22:21 UTC, merged